### ISSUE TITLE
Unable to upload and update profile picture.

### ISSUE THREAD

**Issue by SteveWufeng** [ComputerScienceHouse/profiles#108]
After selecting a profile pic, the correct preview is shown. 
But the "upload image" button does not update the profile pic.

after Select Image
![image](https://user-images.githubusercontent.com/86623538/137609893-75d29e38-d3d4-4c50-8d60-912333a36f1e.png)

after Upload Image
![image](https://user-images.githubusercontent.com/86623538/137609944-b7dfa856-2058-42d1-8e44-bafab89506a7.png)

**Comment by mxmeinhold** [comment]
Is this related to #73?
