### ISSUE TITLE
Twitter Profile Image CORS

### ISSUE THREAD

**Issue by mbillow** [ComputerScienceHouse/profiles#29]
```Access to Image at 'https://twitter.com/{{username}}/profile_image?size=original' from origin 'https://profiles.csh.rit.edu' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://profiles.csh.rit.edu' is therefore not allowed access. The response had HTTP status code 403.```

We should just proxy the image data and serve it instead.

**Comment by evelyndooley** [comment]
Should be fixed in #34 as we now proxy the image data
