### ISSUE TITLE
Profile Picture upload doesn't work

### ISSUE THREAD

**Issue by Scaranman** [ComputerScienceHouse/profiles#42]
After uploading an image to my profile and submitting, said image will not show as profile picture.

**Comment by JDrit** [comment]
what image did you upload?

**Comment by JDrit** [comment]
did you do it at 11:30 this morning?

**Comment by Scaranman** [comment]
I tried uploading it last night and probably at that time too. It's a 160 x 160px jpg image

**Comment by Scaranman** [comment]
I'm assuming it has something to with Eoro's stalker

**Comment by JDrit** [comment]
Can you try again plus send me the image

**Comment by Scaranman** [comment]
Sure.
![14095855_1144233485622962_3761076610529923601_n](https://cloud.githubusercontent.com/assets/21231079/19527977/33ae4634-95f8-11e6-9424-43362341aa87.jpg)

**Comment by JDrit** [comment]
closing due to I  don't care
